# Form implementation generated from reading ui file 'C:/Users/dismo/Desktop/Sensor/circular_splash_screen/splash_screen.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(300, 300)
        SplashScreen.setMinimumSize(QtCore.QSize(300, 300))
        SplashScreen.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QFrame(parent=self.centralwidget)
        self.container.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.container.setObjectName("container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.circle_bg = QtWidgets.QFrame(parent=self.container)
        self.circle_bg.setStyleSheet("QFrame {\n"
"    background-color: #282a36;\n"
"    color: #f8f8f2;\n"
"    border-radius: 120px;\n"
"    font: 9pt \"Segoe UI\";\n"
"\n"
"}")
        self.circle_bg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.circle_bg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.circle_bg.setObjectName("circle_bg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.circle_bg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.texts = QtWidgets.QFrame(parent=self.circle_bg)
        self.texts.setMaximumSize(QtCore.QSize(16777215, 180))
        self.texts.setStyleSheet("background: none;")
        self.texts.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.texts.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.texts.setObjectName("texts")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.texts)
        self.verticalLayout_4.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.texts)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.version = QtWidgets.QLabel(parent=self.frame)
        self.version.setMinimumSize(QtCore.QSize(100, 24))
        self.version.setMaximumSize(QtCore.QSize(100, 24))
        self.version.setStyleSheet("QLabel{\n"
"    background-color: rgb(68, 71, 90);\n"
"    color: rgb(151, 159, 200);\n"
"    border-radius:12px;\n"
"}")
        self.version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.version.setObjectName("version")
        self.verticalLayout_5.addWidget(self.version, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.title = QtWidgets.QLabel(parent=self.texts)
        self.title.setMinimumSize(QtCore.QSize(0, 30))
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.loading = QtWidgets.QLabel(parent=self.texts)
        self.loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loading.setObjectName("loading")
        self.gridLayout.addWidget(self.loading, 3, 0, 1, 1)
        self.empty = QtWidgets.QFrame(parent=self.texts)
        self.empty.setMinimumSize(QtCore.QSize(0, 80))
        self.empty.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.empty.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.empty.setObjectName("empty")
        self.gridLayout.addWidget(self.empty, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.texts)
        self.verticalLayout_2.addWidget(self.circle_bg)
        self.verticalLayout.addWidget(self.container)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Loading..."))
        self.version.setText(_translate("SplashScreen", "v1.0.0 - Beta_1"))
        self.title.setText(_translate("SplashScreen", "PyQt- Modern GUI"))
        self.loading.setText(_translate("SplashScreen", "Loading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec())
